### ISSUE TITLE
Testimonial section unresponsive.

### ISSUE THREAD

**Issue by utk2103** [DevXsphere/Website-devxsphere#14]
- while making PR make sure to share a image with it.
- add a description of the changes you've done.

**Comment by harsh0728** [comment]
assign this issue to me. I will solve this issue

**Comment by harsh0728** [comment]
@utk2103 i have checked Testimonial section is responsive completely
I think you have an misunderstanding because that section is completely responsive

**Comment by utk2103** [comment]
Everything works good
